### ISSUE TITLE
Surface errors in package.json

### ISSUE THREAD

**Issue by MichalBryxi** [CrowdStrike/monorepo-next#365]
Assume I have a syntax error in my `package.json`. Extra comma or something. Then running `yarn task` with `monorepo-next` will just fail with:

> SyntaxError: Unexpected token } in JSON at position 526

Or similar, without any pointers **which** file is problematic. I narrowed it down to [this file and line](https://github.com/CrowdStrike/monorepo-next/blob/main/src/get-workspaces-paths.js#L63) which when changed to:

```diff
- throw err;
+ throw packagePath;
```

will at least give me _some_ information on where is the issue - **which** `package.json` file has the error.

Now I know that would not be a good patch, but just to document this issue so that someone competent can take a look.

**Comment by kellyselden** [comment]
What does something like `yarn install` give you in terms of error message with that malformed package.json?

**Comment by MichalBryxi** [comment]
Sorry, I don't have the access to said repo anymore. I guess this one can be closed.
